Home/urls.py
from django.conf.urls import url
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^$', views.home, name='Home'),

    path('', views.home, name="home_creation_page"),
    path('login/', auth_views.LoginView.as_view(template_name="Home/login.html"), name='login_page'),
    path('logout/', auth_views.LogoutView.as_view(template_name="/"), name='logout_page'),    
    path('signup', views.signup, name="sign_up_page"),
    path('profile', views.profile, name="profile_page"),
    # path('game', views.game, name="game"),
    # path('get_game', views.get_nplayer_game, name="get_game"),
    path('join', views.join, name="join_page"),

    url(r'^account_activation_sent/$', views.account_activation_sent, name='account_activation_sent'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate')
]

IceToMeetYou/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from rest_framework import routers
from IceToMeetYou.API.api import UserViewSet, EventViewSet, GameViewSet, GroupingViewSet, GroupViewSet
from IceToMeetYou.API.auth_api import CustomAuthToken


router = routers.DefaultRouter()
router.register('users', UserViewSet)
router.register('events', EventViewSet)
router.register('games', GameViewSet)
router.register('grouping', GroupingViewSet)
router.register('group', GroupViewSet)

urlpatterns = [
    url(r'^', include(('Home.urls', 'Home'), namespace='Home')),

    path('', include('Home.urls')),
    path('create/', include('creation.urls')),
    path('event/', include('event.urls')),
    path('games/', include('games.urls')),
    path('play/', include('gameplay.urls')),
    path('admin/', admin.site.urls),
    path('oauth/', include('social_django.urls', namespace='social')),  # <-- Social Login
    path('group/', include('group.urls')),
    path('api-auth/', CustomAuthToken.as_view()),
    path('api/', include(router.urls))
]

gameplay/urls.py
from django.urls import path, include
from . import views
from datetime import datetime

urlpatterns = [
    path('<int:event_pk>/begin', views.init_game, name='begin'),
    path('<int:event_pk>/add', views.add_self, name='add_self'),
    path('<int:event_pk>/add_all', views.add_all, name='add_all'),
    path('<int:event_pk>/remove', views.remove_self, name='remove_self'),
    path('<int:event_pk>/end', views.end_game, name='end_game'),
    path('<int:event_pk>/start_round'.format(datetime.now()), views.start_round, name='start_round')
]

games/urls.py
from django.urls import path, include
from . import views
# from django.conf.urls import url

urlpatterns = [
    path('', views.game, name='game'),
    path('<int:pk>/', views.gamesid, name='game_api'),
    path('random', views.get_nplayer_game, name="get_game"),
    path('event', views.get_user_game, name='get_user_game'),
]

gmail/gmail/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

Home/models.py
from __future__ import unicode_literals

from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver

games/models.py
from django.db import models
import random

class GameType(models.Model):
    types_list = (
        ('WUR', 'Would You Rather...?'),
        ('TOD', 'Truth or Dare'),
        ('ACT', 'Activity'),
        ('DIS', 'Discuss'),
        ('OTH', 'Other')
    )
    game_type = models.CharField(max_length=3, choices=types_list)
    min_players = models.IntegerField(default=2)
    max_players = models.IntegerField(default=2)

    def __str__(self):
        return "{}: {} ({}-{} Players)".format(self.game_type,
                                            self.get_game_type_display(),
                                            self.min_players, self.max_players)

class GameManager(models.Manager):
    def nplayer_games(self, num_players):
        min_games = Game.objects.filter(
            game_type__min_players__lte=num_players)
        filtered_games = min_games.filter(
            game_type__max_players__gte=num_players)
        return filtered_games

class Game(models.Model):
    game_type = models.ForeignKey(GameType, default="",
                             on_delete=models.DO_NOTHING)
    text = models.TextField(blank=True)
    objects = GameManager()

    def get_nplayer_games(nplayers):
        min_games = Game.objects.filter(game_type__min_players__gte=nplayers)
        filtered_games = Game.objects.filter(game_type__max_players__lte=nplayers)
        return list(filtered_games)

    def __str__(self):
        type_str = self.game_type.get_game_type_display()
        return "{}: {}".format(type_str, self.text)

Home/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class SignUpForm(UserCreationForm):
    email = forms.EmailField(max_length=254, required=True)

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2',)

class Join(forms.Form):
    #code = forms.CharField(max_length=100, required=True, label='') 
    access_code = forms.CharField(widget=forms.TextInput(attrs={'size':'30','maxlength':'70'} ), label='')

Home/views.py
from .forms import SignUpForm, Join
from creation.models import Event, Group, EventUser
from games.models import Game, GameType
import random

from django.contrib.auth import login, authenticate
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required

# For email verification process
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from .tokens import account_activation_token
from django.urls import reverse
from django.contrib.auth.models import User
from django.core.mail import EmailMessage
from django.core.mail import send_mail


creators = [
    {
        'name': 'Kevin',
        'school': 'Hunter College'
    },
    {
        'name': 'Dandan',
        'school': 'Hunter College'
    },
    {
        'name': 'Silvena',
        'school': 'Hunter College'
    },
    {
        'name': 'Kristoff',
        'school': 'Hunter College'
    }
]


def home(request):
    args = {
        'title': 'Ice2MeetU'
    }
    return render(request, 'Home/home.html', args)

def logout(request):
    return render(request, 'Home/home.html', {})

def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            user_email = form.cleaned_data.get('email')
            # TODO: Validate the email
            current_site = get_current_site(request)
            subject = 'Activate Your Account'
            message = render_to_string('Home/account_activation_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)).decode(),
                'token': account_activation_token.make_token(user),
            })

            email = EmailMessage(
                subject, message, to=[user_email]
            )
            email.send()
    
            return redirect('account_activation_sent')
    else:
        form = SignUpForm()
    return render(request, 'Home/signup.html', {'form': form})


def account_activation_sent(request):
    return render(request, 'Home/account_activation_sent.html')

def confirmed_page(request):
    return render(request, 'Home/account_confirmed_page.html')


def activate(request, uidb64, token, backend='django.contrib.auth.backends.ModelBackend'):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.email_confirmed = True
        user.save()

        return render(request, 'Home/account_confirmed_page.html')
    else:
        return render(request, 'Home/account_activation_invalid.html')


def logon(request):
    if request.method == 'POST':
        user = authenticate(
            username = request.POST.get('username', '').strip(),
            password = request.POST.get('password', ''),
        )

        if user is None:
            messages.error(request, u'Invalid credentials')
        else:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(request.GET.get('next', 'home_creation_page'))
            else:
                messages.error(request, u'User is not active.')

                return render_to_response('Home/login.html', locals(),
                    context_instance=RequestContext(request))
    else:
        return render(request, 'Home/login.html', {})

@login_required(login_url='login/')
def profile(request):
    return render(request, 'Home/home.html', {})

@login_required(login_url='login/')
def join(request):
    if request.method == 'POST':

        form = Join(request.POST)
        try:
            code = form.data['access_code']
            form = Event.objects.get(access_code=code)
        except Event.DoesNotExist:
            content = {
                'form': form,
                'name': 'Invalid Access Code',
                'user' : request.user
            }
            return render(request, 'Home/join.html', content)

        e = Event.objects.get(access_code=code)
        user, created = EventUser.objects.get_or_create(user=request.user)
        for u in e.users():
            if u.user == request.user:
                return HttpResponseRedirect('../event/{}/go'.format(form.access_code))
        user.events.add(e)
        user.save()
        e.event_users.add(user)
        return HttpResponseRedirect('../event/{}/go'.format(form.access_code))
    else:
        form = Join()
    events = Event.objects.filter(event_users__user_id=request.user.id)
    content = {
        'form': form,
        'name': 'Access Code',
        'user' : request.user,
        'events': events,
    }
    return render(request, 'Home/join.html', content)

games/views.py
from django.shortcuts import render
from .models import Game, GameType
from django.contrib.auth.decorators import login_required
import random
from django.http import HttpResponseRedirect, JsonResponse
from django.urls import reverse


@login_required(login_url='../login/')
def get_user_game(request):
    if request.user.eventuser_set.exists():
        user = request.user.eventuser_set.all()[0]
    else:
        raise RuntimeError("Not an event user")
    if user.is_playing():
        game = user.current_game()
        status = 200
        context = {
            'id': game.id,
            'text': game.text,
            'game': game.game_type.get_game_type_display()
        }
    else:
        status = 302
        context = {
            'id': 0,
            'text': "Your Event is not playing right now. If you'd like to \
                    start a random game, please log out and click Start Game.",
            'game': 'Not Playing'
        }
    return JsonResponse(status=status, data=context)

def get_nplayer_game(request):
    if not request.GET:
        status = 400
        err = {
            'id': None,
            'text': 'Please enter number of players',
            'game': None
        }
        return JsonResponse(status=status, data=err)
    nplayers = request.GET.get('nplayers', None)
    filtered_games = Game.objects.nplayer_games(nplayers)
    rand_game = random.choice(filtered_games)
    context = {
        'id': rand_game.id,
        'text': rand_game.text,
        'game': rand_game.game_type.get_game_type_display()
    }
    return JsonResponse(context)

def game(request):
    context = {
        'event_id': 0,
        'event_playing': False,
        'is_playing': False
    }
    try: 
        user = request.user
        if not user.is_authenticated or not user.eventuser_set.exists():
            return render(request, 'Games/game.html', context)
        if user.eventuser_set.exists():
            eventuser = user.eventuser_set.all()[0]
            if eventuser.events.filter(is_playing=True).exists():
                context['event_playing'] = True
                context['event_id'] = eventuser.events.filter(
                    is_playing=True)[0].pk
            if eventuser.is_playing():
                context['event_id'] = eventuser.playing_event().pk
                if eventuser.playing_event().is_playing:
                    context['is_playing'] = True
                    group = eventuser.current_group()
                if not group.is_complete:
                    return HttpResponseRedirect(reverse('same_group_page'))
    except AttributeError:
        pass #AnonUser
    print(context)
    return render(request, 'Games/game.html', context)

def gamesid(request, pk):
    try:
        game = Game.objects.get(pk=pk)
    except Game.DoesNotExist:
        err = {
            'text': "Error: Game ID {} does not exist".format(pk)
        }
        return JsonResponse(status=404, data=err)

    context = {
        'id': game.id,
        'text': game.text,
        'game': game.game_type.get_game_type_display()
    }
    return JsonResponse(context)

Home/templates/Home/account_activation_email.html
{% autoescape off %}
Hi {{ user.username }},

Please click on the link below to confirm your registration:

http://{{ domain }}{% url 'Home:activate' uidb64=uid token=token %}
{% endautoescape %}

Home/templates/Home/account_activation_invalid.html
{% extends "Home/base.html" %}

{% block content %}
  <p>The confirmation link was invalid, possibly because it has already been used.</p>
{% endblock %}

Home/templates/Home/account_activation_sent.html
{% extends "Home/base.html" %}

{% block content %}
<div style="margin-top: 200px">
  <p>Please confirm your email address to complete the registration. </p>
</div>
  
{% endblock %}

Home/templates/Home/account_confirmed_page.html
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<link href="/static/assets/css/email.css" rel="stylesheet" type="text/css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

<div class="container register" style="height: 80%; width: 100%; margin-top: 5%;">
    <div class="row">
        <div class="col-md-4 register-left">
            <img src="https://image.ibb.co/n7oTvU/logo_white.png" alt=""/>
            <h3>Welcome</h3>
            <p>You are 5 seconds away from activating your private account</p>
        </div>
        <div class="col-md-8 register-right">
            <div class="tab-content" id="myTabContent">
                <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                    <h3 class="register-heading">Nice to Meet You</h3>
                    <div class="row register-form">
                        <p> Thank you for confirming your email address.</p>
                        <br>
                        <p> You will be redirect to the home page in <span id="countdown">6</span> seconds</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    // Total seconds to wait
    var seconds = 5;
    function countdown() {
        seconds = seconds - 1;
        if (seconds <= 0) {
            // Chnage your redirection link here
            window.location.href = "/";
        } else {
            // Update remaining seconds
            document.getElementById("countdown").innerHTML = seconds;
            // Count down using javascript
            window.setTimeout("countdown()", 1000);
        }
    }
    // Run countdown function
    countdown();
</script>

Home/templates/Home/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
        crossorigin="anonymous">

    <!-- Custom fonts for Home Nav template -->
    <link href="{% static 'assets/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
    
    <!-- Plugin CSS -->
    <link href="{% static 'assets/vendor/magnific-popup/magnific-popup.css' %}" rel="stylesheet" type="text/css">

    <!-- Custom styles for Home Nav template -->
    <link rel="stylesheet" type="text/css" media="all" href="{% static 'assets/css/home.css' %}"/>
    <link rel="shortcut icon" href="#" />
    
    {% if title %}
    <title>{{ title }}</title>
    {% else %}
    <title>Ice2MeetU</title>
    {% endif %}
</head>

<body id="page-top">
  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg bg-secondary fixed-top text-uppercase" id="mainNav">
    <div class="container">
      <a class="navbar-brand js-scroll-trigger" href="{% url 'home_creation_page' %}">Ice2MeetU</a>
      <button class="navbar-toggler navbar-toggler-right text-uppercase bg-primary text-white rounded" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>

      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          {% if user.is_authenticated %}
          <li class="nav-item mx-0 mx-lg-1">
            <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'creation_page' %}">
              Create Event
            </a>
          </li>

          <li class="nav-item mx-0 mx-lg-1">
            <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'join_page' %}">
              Join Event
            </a>
          </li>

          <li class="nav-item mx-0 mx-lg-1">
            <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'game' %}">
              Start Game
            </a>
          </li>

          <li class="nav-item mx-0 mx-lg-1">
            <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'logout_page' %}">
              Log Out
            </a>
          </li>
          {% else %}
          <li class="nav-item mx-0 mx-lg-1">
            <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'sign_up_page' %}">Sign Up</a>
          </li>

          <li class="nav-item mx-0 mx-lg-1">
            <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'home_creation_page' %}#menu">Menu</a>
          </li>

          <li class="nav-item mx-0 mx-lg-1">
            <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'home_creation_page' %}#portfolio">About</a>
          </li>

          <li class="nav-item mx-0 mx-lg-1">
            <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'home_creation_page' %}#team">Team</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>
  {% block content %} {% endblock %}
  
  <!-- Footer -->
  <div class="copyright py-4 text-center text-white">
    <div class="container">
      <small>Copyright &copy; Ice2MeetU 2018</small>
    </div>
  </div>

  <!-- Scroll to Top Button (Only visible on small and extra-small screen sizes) -->
  <div class="scroll-to-top d-lg-none position-fixed ">
    <a class="js-scroll-trigger d-block text-center text-white rounded" href="#page-top">
      <i class="fa fa-chevron-up"></i>
    </a>
  </div>

  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'assets/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Plugin JavaScript -->
  <script src="{% static 'assets/vendor/jquery-easing/jquery.easing.min.js' %}"></script>
  <script src="{% static 'assets/vendor/magnific-popup/jquery.magnific-popup.min.js' %}"></script>

  <!-- Custom scripts for this template -->
  <script src="{% static 'assets/js/home.js' %}"></script>

</body>


</html>

Home/templates/Home/login.html
{% load staticfiles %}
<!DOCTYPE HTML>
<html>
<head>
<title>Login Form</title>
<!-- Custom Theme files -->
<link rel="stylesheet" type="text/css" media="all" href="{% static 'assets/css/signup_style.css' %}"/>
<!-- for-mobile-apps -->
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" /> 
<!-- font-awesome icons -->
<link rel="stylesheet" href="{% static 'assets/css/font-awesome.css' %}"/>
<!--Google Fonts-->
<link href="//fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i" rel="stylesheet">
</head>
    <body>
        <div class="wthree-dot">
            <h1>Login Form</h1>
            <div class="profile">
                <div class="wrap">
                    <div class="wthree-grids">
                        <div class="content-left-login">
                            <div class="content-info">
                                <h2>Brief History About Us</h2>
                                <div class="slider">
                                    <div class="callbacks_container">
                                        <ul class="rslides callbacks callbacks1" id="slider4">
                                            <li>
                                                <div class="w3layouts-banner-info">
                                                    <h3>The Team</h3>
                                                    <p>We are a group of CS students from Hunter College </p>
                                                </div>
                                            </li>
                                        </ul>
                                    </div>
                                    <div class="clear"></div>
                                </div>
                                <div class="agileinfo-follow">
                                    <h4>Login with</h4>
                                </div>
                                <div class="agileinfo-social-grids">
                                    <ul>
                                        <a href="{% url 'social:begin' 'github' %}"><i class="fa fa-github"></i></a>
                                        <a href="{% url 'social:begin' 'facebook' %}"><i class="fa fa-facebook"></i></a>
                                        <!-- <a href="{% url 'social:begin' 'twitter' %}"><i class="fa fa-twitter"></i></a> -->
                                        <!-- <a href="{% url 'social:begin' 'linkedin' %}"><i class="fa fa-linkedin" aria-hidden="true"></i></a> -->
                                    </ul>
                                </div>
                                <br>
                                <div class="agile-signin">
                                    <h4>Don't have an account? <a href="/signup">Sign Up</a></h4>
                                </div>
                            </div>
                        </div>
                        <div class="content-main-login">
                            <div class="w3ls-subscribe">
                                <h4>Returning User?</h4>
                                <form action="{% url 'login_page' %}" method="post">
                                    {% csrf_token %}
                                    <small style="color: white">{{ form.username.label }}</small>
                                    {{ form.username }}
                                    <small style="color: white">{{ form.password.label }}</small>
                                    {{ form.password }}
                                    <div></div>
                                    <br>
                                    <input type="submit" value="Login">
                                    <br>
                                    <br>
                                    <input type="submit" value="Forgot Password">
                                </form>
                            </div>
                        </div>
                        <!-- <div class="clear"> </div> -->
                    </div>
                    
                    <div class="wthree_footer_copy">
                    </div>
                </div>
            </div>
        </div>
        <script>
            // You can also use "$(window).load(function() {"
            $(function () {
                // Slideshow 4
                $("#slider4").responsiveSlides({
                auto: true,
                pager:true,
                nav:false,
                speed: 400,
                namespace: "callbacks",
                before: function () {
                    $('.events').append("<li>before event fired.</li>");
                },
                after: function () {
                    $('.events').append("<li>after event fired.</li>");
                }
                });

            });
        </script>
    </body>
</html>

Home/templates/Home/signup.html
{% load staticfiles %}

<!DOCTYPE HTML>
<html>
	<head>
		<title>Signup Form</title>
		<!-- Custom Theme files -->
		<link rel="stylesheet" type="text/css" media="all" href="{% static 'assets/css/signup_style.css' %}"/>
		<!-- for-mobile-apps -->
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" /> 
		<!-- font-awesome icons -->
		<link rel="stylesheet" href="{% static 'assets/css/font-awesome.css' %}"/>
		<!--Google Fonts-->
		<link href="//fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i" rel="stylesheet">
	</head>
	<body>
		<div class="wthree-dot">
			<h1>Signup Form</h1>
			<div class="profile">
				<div class="wrap">
					<div class="wthree-grids">
						<div class="content-left-signup">
							<div class="content-info">
								<h2>Brief History About Us</h2>
								<div class="slider">
									<div class="callbacks_container">
										<ul class="rslides callbacks callbacks1" id="slider4">
											<li>
												<div class="w3layouts-banner-info">
													<h3>The Team</h3>
													<p>We are a group of CS students from Hunter College, who are enthusiastic about technology and want to make positive impact on society. </p>
												</div>
											</li>
										</ul>
									</div>
									<div class="clear"></div>
								</div>
								<div class="agileinfo-follow">
									<h4>Sign Up with</h4>
								</div>
								<div class="agileinfo-social-grids">
									<ul>
											<a href="{% url 'social:begin' 'github' %}"><i class="fa fa-github"></i></a>
											<a href="{% url 'social:begin' 'facebook' %}"><i class="fa fa-facebook"></i></a>
											<!-- <a href="{% url 'social:begin' 'twitter' %}"><i class="fa fa-twitter"></i></a> -->
											<!-- <a href="{% url 'social:begin' 'linkedin' %}"><i class="fa fa-linkedin" aria-hidden="true"></i></a> -->
									</ul>
								</div>
								<div class="agile-signin">
									<h4>Already have an account <a href="/login">Sign In</a></h4>
								</div>
							</div>
						</div>
						<div class="content-main-signup">
							<div class="w3ls-subscribe">
								<h4>New Customer?</h4>
								<form action="{% url 'sign_up_page' %}" method="post">
									{% csrf_token %}
									<small style="color: white">{{ form.username.label }}</small>
									{{ form.username }}
									<small style="color: white">{{ form.email.label }}</small>
									{{ form.email }}
									<small style="color: white">{{ form.password1.label }}</small>
									{{ form.password1 }}
									<small style="color: white">{{ form.password2.label }}</small>
									{{ form.password2 }}
									<input type="submit" value="Sign Up">
								</form>
							</div>
						</div>
						<div class="clear"> </div>
					</div>
					<div class="wthree_footer_copy">
					</div>
				</div>
			</div>
		</div>
		<script>
			// You can also use "$(window).load(function() {"
			$(function () {
			// Slideshow 4
			$("#slider4").responsiveSlides({
				auto: true,
				pager:true,
				nav:false,
				speed: 400,
				namespace: "callbacks",
				before: function () {
				$('.events').append("<li>before event fired.</li>");
				},
				after: function () {
				$('.events').append("<li>after event fired.</li>");
				}
			});
		
			});
		</script>
	</body>
</html>